version: "3.8"
volumes:
  avito:
  avitoTest:
services:
  db:
    image: postgres:13.3
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${VOLUME}:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
        ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
  goose:
    build:
      context: ./db
      dockerfile: goose.dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  avserver:
    build:
      context: ./
      dockerfile: Dockerfile
    command: [
      "-serverPort=${HTTP_PORT}",

      "-dbHost=${POSTGRES_HOST}",
      "-dbPort=${POSTGRES_PORT}",
      "-dbUsername=${POSTGRES_USER}",
      "-dbPassword=${POSTGRES_PASSWORD}",
      "-dbName=${POSTGRES_DB}"
    ]
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    restart: always
    depends_on:
      db:
        condition: service_healthy
      goose:
        condition: service_completed_successfully